version: "3.7"

services: 
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "TRFastApi"
      MYSQL_USER: "NTR212"
      MYSQL_PASSWORD: "petclinic"
    ports:
      - 3306:3306
    networks:
      - local-net
    
  server:
    links: 
      - mysql
    container_name: server
    build: ./servises
    image: server-api
    ports:
      - 5000:5000
    networks:
     - local-net

networks:
  local-net:
    driver: bridge    
