version: "3.7"

services: 
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    # uncoment to persist data
    # volumes:
    #   - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "TRFastApi"
      MYSQL_USER: "NTR212"
      MYSQL_PASSWORD: "petclinic"
    ports:
      - 3306:3306
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      timeout: 10s
      retries: 10      
    networks:
      - local-net
    
  server:
    links: 
      - mysql
    container_name: server
    build: ./servises
    image: server-api
    ports:
      - 5000:5000
    restart: on-failure
    networks:
     - local-net
    depends_on:
      mysql:
        condition: service_healthy

networks:
  local-net:
    driver: bridge    
